# Generated by Django 5.0.6 on 2024-06-07 13:55

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_image_post_thumbnail_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetopic',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
