# Generated by Django 5.0.6 on 2024-06-09 16:01

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_coursetopic_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetopic',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
