# Generated by Django 5.0.6 on 2024-06-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_profile_address_profile_email_profile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetopic',
            name='body',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
