# Generated by Django 5.0.6 on 2024-06-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_coursetopic_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetopic',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
